export const patients = [
  {
    studentId: 1,
    studentName: "Charlene Reed ",
    matNumber: "FSC/CSC/01901567",
    department: "Computer Science",
    yearOfAddmission: "2019",
    religion: "Christian",
    gender: "female",
    hostel: "Hall 1",
    bloodGroup: "A+",
    dob: "19th Feb. 2002",
    description: "Allergies: dust, milk",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 2,
    studentName: "Thomas Wayne",
    matNumber: "FSC/CSC/01901643",
    department: "Biochemistry",
    yearOfAddmission: "2018",
    religion: "Christian",
    gender: "male",
    hostel: "Hall 2",
    bloodGroup: "O",
    dob: "19th Feb. 2002",
    description: "Allergies: dust, milk",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 3,
    studentName: "Jerry Steele",
    matNumber: "ENG/COE/01901533",
    department: "Computer Engineering",
    yearOfAddmission: "2022",
    religion: "Christian",
    gender: "male",
    hostel: "Hall 3",
    bloodGroup: "B-",
    dob: "19th Feb. 2002",
    description: "Allergies: dust",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 4,
    studentName: "Oshioke Salaki",
    matNumber: "FSC/MCB/01901533",
    department: "Microbiology",
    yearOfAddmission: "2021",
    religion: "Christian",
    gender: "male",
    hostel: "Hall 3",
    bloodGroup: "B-",
    dob: "1st Jan. 2003",
    description: "Allergies: dust",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 5,
    studentName: "Maimuna Usman",
    matNumber: "FAM/POL/01901234",
    department: "Political Science",
    yearOfAddmission: "2020",
    religion: "Christian",
    gender: "female",
    hostel: "Hall 4",
    bloodGroup: "B-",
    dob: "19th Feb. 2002",
    description: "Allergies: dust",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 6,
    studentName: "Jerry Steele",
    matNumber: "ENG/COE/01901533",
    department: "Computer Engineering",
    yearOfAddmission: "2022",
    religion: "Christian",
    gender: "male",
    hostel: "Hall 3",
    bloodGroup: "B-",
    dob: "19th Feb. 2002",
    description: "Allergies: dust",
    lastVisit: null,
    pastVisits: [],
  },
  {
    studentId: 7,
    studentName: "Jerry Steele",
    matNumber: "ENG/COE/01901533",
    department: "Computer Engineering",
    yearOfAddmission: "2022",
    religion: "Christian",
    gender: "male",
    hostel: "Hall 3",
    bloodGroup: "B-",
    dob: "19th Feb. 2002",
    description: "Allergies: dust",
    lastVisit: null,
    pastVisits: [],
  },
];
